import { Habit, Transaction, CareerMilestone, AIEvaluationResult } from '../types';
import { getTodayDateStr, addDays } from './dateUtils';

// Helper to pre-seed mathematically authentic streak history up to yesterday
function getPastConsecutiveDates(count: number): string[] {
  const dates: string[] = [];
  const today = getTodayDateStr();
  for (let i = 1; i <= count; i++) {
    dates.push(addDays(today, -i));
  }
  return dates.reverse();
}

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h-1',
    title: 'Morning Prayer & Spiritual Reflection',
    description: 'Dedicate 20 minutes to morning gratitude, meditation, and quiet focus.',
    category: 'religion',
    isDaily: true,
    completedDates: getPastConsecutiveDates(6),
    targetDurationMinutes: 20,
    timeOfDay: 'morning',
    priority: 'high',
    streak: 6,
    bestStreak: 14,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-2',
    title: 'Solve 2 LeetCode / DSA Problems',
    description: 'Focus on Trees, Graphs, or Dynamic Programming patterns.',
    category: 'career',
    isDaily: true,
    completedDates: getPastConsecutiveDates(4),
    targetDurationMinutes: 45,
    timeOfDay: 'morning',
    priority: 'high',
    streak: 4,
    bestStreak: 12,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-3',
    title: '45-Min Gym Workout or 8k Steps',
    description: 'Resistance training or zone 2 cardiovascular conditioning.',
    category: 'health',
    isDaily: true,
    completedDates: getPastConsecutiveDates(8),
    targetDurationMinutes: 45,
    timeOfDay: 'afternoon',
    priority: 'high',
    streak: 8,
    bestStreak: 21,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-4',
    title: 'Read 25 Pages of Engineering Book',
    description: 'Designing Data-Intensive Applications or System Design Interview.',
    category: 'education',
    isDaily: true,
    completedDates: getPastConsecutiveDates(3),
    targetDurationMinutes: 30,
    timeOfDay: 'evening',
    priority: 'medium',
    streak: 3,
    bestStreak: 9,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-5',
    title: 'Call Family & Meaningful Connection',
    description: 'Check in with parents or close mentors without phone multitasking.',
    category: 'social',
    isDaily: true,
    completedDates: getPastConsecutiveDates(5),
    targetDurationMinutes: 15,
    timeOfDay: 'evening',
    priority: 'medium',
    streak: 5,
    bestStreak: 10,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-6',
    title: 'Nightly Reflection & Gratitude Log',
    description: 'Review today’s wins, clear mental clutter, plan top 3 for tomorrow.',
    category: 'religion',
    isDaily: true,
    completedDates: getPastConsecutiveDates(7),
    targetDurationMinutes: 10,
    timeOfDay: 'evening',
    priority: 'medium',
    streak: 7,
    bestStreak: 15,
    createdAt: '2026-09-01T08:00:00.000Z',
  },
  {
    id: 'h-7',
    title: 'Ship Architecture RFC for Async Queue',
    description: 'Write one-time proposal document for worker task scaling.',
    category: 'career',
    isDaily: false, // One-time task
    completedDates: [],
    targetDurationMinutes: 90,
    timeOfDay: 'afternoon',
    priority: 'high',
    streak: 0,
    bestStreak: 0,
    createdAt: '2026-09-10T10:00:00.000Z',
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-1',
    type: 'income',
    amount: 6850,
    category: 'Engineering Salary',
    description: 'Monthly Senior SWE Base Compensation',
    date: '2026-09-01',
    paymentMethod: 'Direct Deposit',
    createdAt: '2026-09-01T12:00:00.000Z',
  },
  {
    id: 'tx-2',
    type: 'income',
    amount: 1400,
    category: 'Consulting / Freelance',
    description: 'System Architecture advisory for startup',
    date: '2026-09-05',
    paymentMethod: 'Stripe Transfer',
    createdAt: '2026-09-05T14:30:00.000Z',
  },
  {
    id: 'tx-3',
    type: 'savings',
    amount: 2200,
    category: 'Index Funds & S&P 500',
    description: 'Automated dollar cost averaging into Vanguard ETF',
    date: '2026-09-02',
    paymentMethod: 'Bank Transfer',
    createdAt: '2026-09-02T09:00:00.000Z',
  },
  {
    id: 'tx-4',
    type: 'expense',
    amount: 1750,
    category: 'Housing & Utilities',
    description: 'Apartment rent, electric, high-speed fiber internet',
    date: '2026-09-01',
    paymentMethod: 'ACH Transfer',
    createdAt: '2026-09-01T10:00:00.000Z',
  },
  {
    id: 'tx-5',
    type: 'expense',
    amount: 480,
    category: 'Food & Nutrition',
    description: 'Weekly organic groceries and clean meal preps',
    date: '2026-09-06',
    paymentMethod: 'Credit Card',
    createdAt: '2026-09-06T17:00:00.000Z',
  },
  {
    id: 'tx-6',
    type: 'expense',
    amount: 120,
    category: 'Tech & Learning',
    description: 'Cloud server lab credits & LeetCode Premium subscription',
    date: '2026-09-08',
    paymentMethod: 'Credit Card',
    createdAt: '2026-09-08T11:20:00.000Z',
  },
  {
    id: 'tx-7',
    type: 'expense',
    amount: 95,
    category: 'Health & Gym',
    description: 'Gym membership and recovery sauna pass',
    date: '2026-09-03',
    paymentMethod: 'Credit Card',
    createdAt: '2026-09-03T08:15:00.000Z',
  },
  {
    id: 'tx-8',
    type: 'savings',
    amount: 600,
    category: 'Emergency Reserve',
    description: 'High yield savings account deposit',
    date: '2026-09-09',
    paymentMethod: 'Bank Transfer',
    createdAt: '2026-09-09T16:00:00.000Z',
  },
];

export const INITIAL_CAREER_MILESTONES: CareerMilestone[] = [
  // DSA
  {
    id: 'cm-1',
    pillar: 'dsa',
    level: 'junior',
    title: 'Core Data Structures Mastery',
    description: 'Implement Arrays, Linked Lists, Stacks, Queues, and Hash Maps from scratch.',
    topics: ['Hash Tables', 'Pointers', 'Big-O Analysis', 'Recursion'],
    completed: true,
    completedAt: '2026-08-15',
    targetCount: 50,
    currentCount: 50,
  },
  {
    id: 'cm-2',
    pillar: 'dsa',
    level: 'mid',
    title: 'Advanced Tree & Graph Algorithms',
    description: 'Master Binary Search Trees, BFS/DFS, Dijkstra, Topological Sort, and Trie implementations.',
    topics: ['BFS/DFS', 'Binary Trees', 'Disjoint Set', 'Heap / Priority Queue'],
    completed: true,
    completedAt: '2026-09-02',
    targetCount: 75,
    currentCount: 75,
  },
  {
    id: 'cm-3',
    pillar: 'dsa',
    level: 'senior',
    title: 'Dynamic Programming & Hard Patterns',
    description: 'Solve 1D/2D DP, Knapsack variants, Bit Manipulation, and Monotonic Queue problems under 25 mins.',
    topics: ['Dynamic Programming', 'Memoization', 'Segment Trees', 'Sliding Window'],
    completed: false,
    targetCount: 60,
    currentCount: 38,
  },
  {
    id: 'cm-4',
    pillar: 'dsa',
    level: 'lead',
    title: 'Competitive Interview Benchmarking & Mentorship',
    description: 'Conduct 10+ mock technical interviews and author algorithmic interview problem rubrics.',
    topics: ['Mock Interviews', 'Algorithm Design', 'Optimization Rubrics'],
    completed: false,
    targetCount: 15,
    currentCount: 6,
  },

  // System Design
  {
    id: 'cm-5',
    pillar: 'system_design',
    level: 'junior',
    title: 'REST APIs & Relational DB Schema Design',
    description: 'Design normalized SQL tables, write indexing strategies, and build idempotent REST endpoints.',
    topics: ['PostgreSQL Schema', 'Foreign Keys', 'B-Tree Indexes', 'HTTP Status Codes'],
    completed: true,
    completedAt: '2026-08-20',
    targetCount: 10,
    currentCount: 10,
  },
  {
    id: 'cm-6',
    pillar: 'system_design',
    level: 'mid',
    title: 'Caching, Rate Limiting & Message Queues',
    description: 'Design distributed caching (Redis), Token Bucket rate limiters, and pub/sub async queues (Kafka/RabbitMQ).',
    topics: ['Redis Cache-Aside', 'Kafka Pub/Sub', 'Dead Letter Queues', 'Connection Pooling'],
    completed: true,
    completedAt: '2026-09-08',
    targetCount: 8,
    currentCount: 8,
  },
  {
    id: 'cm-7',
    pillar: 'system_design',
    level: 'senior',
    title: 'High-Scale Distributed Architectures',
    description: 'Design Twitter/X Feed, Uber Ride Matching, and Global Distributed Key-Value Store with CAP trade-offs.',
    topics: ['Consistent Hashing', 'Database Sharding', 'Raft Consensus', 'Multi-Region Replication'],
    completed: false,
    targetCount: 12,
    currentCount: 7,
  },
  {
    id: 'cm-8',
    pillar: 'system_design',
    level: 'lead',
    title: 'Enterprise Architecture & Reliability Strategy',
    description: 'Establish Disaster Recovery (RTO/RPO < 5 mins), zero-downtime database migrations, and SLO budgets.',
    topics: ['Multi-Cloud DR', 'Schema Zero-Downtime', 'Chaos Engineering', 'Cost Optimization'],
    completed: false,
    targetCount: 5,
    currentCount: 2,
  },

  // Full-Stack Mastery
  {
    id: 'cm-9',
    pillar: 'fullstack',
    level: 'junior',
    title: 'Modern TypeScript, React 19 & State Flow',
    description: 'Master strict TypeScript typings, custom hooks, component isolation, and clean UI state.',
    topics: ['TypeScript Generics', 'React 19 Hooks', 'Tailwind CSS', 'Vite Bundler'],
    completed: true,
    completedAt: '2026-08-10',
    targetCount: 1,
    currentCount: 1,
  },
  {
    id: 'cm-10',
    pillar: 'fullstack',
    level: 'mid',
    title: 'Production Backend Microservices & Auth',
    description: 'Implement JWT/OAuth2 authentication, RBAC authorization, and streaming SSE endpoints.',
    topics: ['OAuth2 / GSI', 'Row Level Security', 'Server-Sent Events', 'Express Middleware'],
    completed: true,
    completedAt: '2026-09-04',
    targetCount: 1,
    currentCount: 1,
  },
  {
    id: 'cm-11',
    pillar: 'fullstack',
    level: 'senior',
    title: 'Real-Time WebSockets & Offline-First Sync',
    description: 'Build bi-directional WebSocket pipelines with conflict-free replicated data types and local cache sync.',
    topics: ['WebSockets', 'Optimistic UI', 'CRDTs', 'Worker Threads'],
    completed: false,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'cm-12',
    pillar: 'fullstack',
    level: 'lead',
    title: 'Design System & Monorepo Architecture',
    description: 'Architect cross-team component libraries, micro-frontends, and automated bundle analysis.',
    topics: ['Turborepo', 'Core Web Vitals', 'Design Tokens', 'Accessibility WCAG AAA'],
    completed: false,
    targetCount: 1,
    currentCount: 0,
  },

  // Cloud & DevOps
  {
    id: 'cm-13',
    pillar: 'cloud_devops',
    level: 'junior',
    title: 'Dockerization & Container Hygiene',
    description: 'Write multi-stage Dockerfiles, minimize image sizes, and configure local docker-compose stacks.',
    topics: ['Docker Multi-stage', 'Alpine Base', 'Layer Caching', 'Environment Secrets'],
    completed: true,
    completedAt: '2026-08-18',
    targetCount: 1,
    currentCount: 1,
  },
  {
    id: 'cm-14',
    pillar: 'cloud_devops',
    level: 'mid',
    title: 'CI/CD Pipelines & Automated Testing',
    description: 'Build GitHub Actions or GitLab pipelines with linting, unit tests, integration tests, and security scans.',
    topics: ['GitHub Actions', 'Docker Registry', 'Branch Protections', 'E2E Testing'],
    completed: true,
    completedAt: '2026-09-07',
    targetCount: 1,
    currentCount: 1,
  },
  {
    id: 'cm-15',
    pillar: 'cloud_devops',
    level: 'senior',
    title: 'Kubernetes & Infrastructure as Code (Terraform)',
    description: 'Deploy auto-scaling K8s pods with ingress controllers, HPA, and declarative Terraform modules.',
    topics: ['Kubernetes Helm', 'Terraform Modules', 'Ingress Nginx', 'Prometheus & Grafana'],
    completed: false,
    targetCount: 1,
    currentCount: 0,
  },
  {
    id: 'cm-16',
    pillar: 'cloud_devops',
    level: 'lead',
    title: 'Zero-Trust Security & Multi-Cluster Ops',
    description: 'Implement mTLS service mesh (Istio), automated canary deployments, and SOC2 compliance automation.',
    topics: ['Service Mesh', 'ArgoCD GitOps', 'Vault Secrets', 'Observability Tracing'],
    completed: false,
    targetCount: 1,
    currentCount: 0,
  },
];

export const INITIAL_EVALUATION: AIEvaluationResult = {
  id: 'eval-sample',
  date: new Date().toISOString().split('T')[0],
  overallScore: 84,
  grade: 'A',
  verdict: 'High-velocity execution today. You demonstrated exceptional discipline in morning spiritual grounding, technical career milestones, and savings rate. Continue elevating physical recovery.',
  dimensions: [
    {
      name: 'Education',
      score: 85,
      feedback: 'Great reading pace and technical literature retention. Keep taking structured synthesis notes.',
      status: 'optimal',
    },
    {
      name: 'Religion',
      score: 92,
      feedback: 'Superb intentionality and spiritual presence. Morning and evening reflections completed.',
      status: 'optimal',
    },
    {
      name: 'Health',
      score: 74,
      feedback: 'Good hydration and cardiovascular baseline. Ensure sleep time is locked in by 10:30 PM.',
      status: 'optimal',
    },
    {
      name: 'Social',
      score: 80,
      feedback: 'High quality relational warmth. Check-in with family was meaningful and uninterrupted.',
      status: 'optimal',
    },
    {
      name: 'Career',
      score: 88,
      feedback: 'Strong DSA problem solving and architecture RFC momentum. Consistent senior engineer pace.',
      status: 'optimal',
    },
  ],
  actionItems: [
    'Tackle the Dynamic Programming knapsack milestone first thing tomorrow morning.',
    'Schedule 45 minutes of heavy resistance training before lunch.',
    'Log your weekly financial savings transfer to sustain the 38% monthly savings rate.',
  ],
  stoicQuote: '“No man is free who is not master of himself.” — Epictetus',
  aiGenerated: true,
  createdAt: new Date().toISOString(),
};
